### PR TITLE
Sru1048

### PR DESCRIPTION
**Pull request by zli909**
## Part Description
Created inductor device and added SRU1048 part

## Additional Information
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*

## Checklist
- [ ] Did you create any new schematics or boards?
- - [ ] Did you *make a PR* for them in `circuits-2022`? If so, please pause until you get this PR merged.
- [ ] Did you pull `main` into your branch?
- - [ ] Did you *check for merge conflicts*?
- - [ ] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
- [ ] Did you fill out the above template?
- [ ] Did you assign the right people for review (on the right)?
- [ ] Did you comply with the library style guidelines?

### CODE REVIEW

**Review by 19etweinstock — DISMISSED** [review]
Part name for inductor should not be specific inductor instance
Please make description follow capacitor and resistor
Inductor package outlines should all have equal length

**Comment by zli909** [comment]
Part name is not of specific inductor instance but of package name, given there is no better way to name the footprint. Other issues fixed.

**Comment by 19etweinstock** [comment]
Manufacturer name not consistent with style guide
Attributes not consistent with style guide (old and new)

**Comment by zli909** [comment]
Sep into temp lib, added attributes, fixed manf. name

**Review by Arvind-Srinivasan — APPROVED** [review]
Good

**Pull request merged**
