### PR TITLE
Added LTC3639 device

### PR DESCRIPTION
**Pull request by zli909**
New LTC3639 symbol, new MSE16(12) footprint, new LTC3639 device

## Part Description
LTC3639 Step down DCDC converter.

## Additional Information
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*

## Checklist
- [ ] Did you create any new schematics or boards?
- - [ ] Did you *make a PR* for them in `circuits-2022`? If so, please pause until you get this PR merged.
- [ ] Did you pull `main` into your branch?
- - [ ] Did you *check for merge conflicts*?
- - [ ] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
- [ ] Did you fill out the above template?
- [ ] Did you assign the right people for review (on the right)?
- [ ] Did you comply with the library style guidelines?

### CODE REVIEW

**Comment by 19etweinstock** [comment]
Should we be putting images of symbols and footprints in the pull request. I think I just made this up but it would be very nice, especially if there's only one part.

**Review by 19etweinstock — CHANGES_REQUESTED** [review]
Failed to set prefix
Manufacturer name does not comply with style guide
Description as a sentence is not consistent with the rest of the library. 
Two spaces between words is just bad grammar.
Dot not needed on package since it is not symmetrical.
I would consider connecting the program pins  internally to the SS pins.
TempLibrary should not be merged into main library until PR is approved

**Review by ckaminsky7 — COMMENTED** [review]
I disagree with Ethan about internally connecting the programing pins and ss pins.

**Comment by zli909** [comment]
Fixed requested changes. Added DCDC prefix for DCDC converters to part and style guide

**Comment by 19etweinstock** [comment]
Marked if resolved
- [ ] Failed to set prefix
- [x] Manufacturer name does not comply with style guide
- [x] Description as a sentence is not consistent with the rest of the library.
- [x] Two spaces between words is just bad grammar.
- [x] Dot not needed on package since it is not symmetrical.
- [x] I would consider connecting the program pins internally to the SS pins.
- [ ] TempLibrary should not be merged into main library until PR is approved

Prefix set incorrectly
Style guide should not be updated
Failed to recreate temp library

**Comment by zli909** [comment]
done

**Review by Arvind-Srinivasan — APPROVED** [review]
Good

**Pull request merged**
