### PR TITLE
Add Sunstone DRUs

### PR DESCRIPTION
**Pull request by zli909**
Added 2, 4, and 6 layers DR files for Sunstone Circuits

# Pull Request (PR) into Circuits-Support-2022

***Your PR should not cause any merge conflicts, so please merge the `main` branch into your branch before submitting. It is your responsibility to ensure that the merge does not break something before submitting. [Here](https://guides.github.com/features/mastering-markdown/) is a good resource for markdown formatting as you fill out this template. See this [example](https://github.com/hytech-racing/circuits-support-2020/pull/9). Feel free to ask any electrical lead if you have any questions! Delete this block when actually making your PR!***

## Part Description
*Describe the contents of the pull request. List all the devices you added. Also list any footprints or symbols you modified. If changing other supporting files, please give details on what those changes are.*

## Additional Information
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*

## Checklist
- [ ] Did you create any new schematics or boards?
- - [ ] Did you *make a PR* for them in `circuits-2022`? If so, please pause until you get this PR merged.
- [ ] Did you pull `main` into your branch?
- - [ ] Did you *check for merge conflicts*?
- - [ ] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
- [ ] Did you fill out the above template?
- [ ] Did you assign the right people for review (on the right)?
- [ ] Did you comply with the library style guidelines?

### CODE REVIEW

**Review by Arvind-Srinivasan — COMMENTED** [review]
The DRC files fail to link to their sources on the info screen, and don't look consistent.

**Comment by Arvind-Srinivasan** [comment]
Do we know sunstones specs don't break any of our "default" drc files that work on any fab?

**Review by Arvind-Srinivasan — CHANGES_REQUESTED** [review]
Make a 1 layer and 2 oz 2 layer DRC now as well

**Comment by zli909** [comment]
> Do we know sunstones specs don't break any of our "default" drc files that work on any fab?

Not confirmed, but on BMS rev13 it only threw clearance and dimension errors, and since their mins are larger than advanced, if advanced doesn't break it,  then sunstone's theoretically shouldn't either.

**Review by Arvind-Srinivasan — APPROVED** [review]

**Pull request merged**
