### PR TITLE
Lr8

### PR DESCRIPTION
**Pull request by zli909**
## Part Description
LR8 adjustable linear regulator

## Additional Information
*All datasheets, information, and/or useful links should be included in the Description within EAGLE.*

## Checklist
- [ ] Did you create any new schematics or boards?
- - [ ] Did you *make a PR* for them in `circuits-2022`? If so, please pause until you get this PR merged.
- [ ] Did you pull `main` into your branch?
- - [ ] Did you *check for merge conflicts*?
- - [ ] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
- [ ] Did you fill out the above template?
- [ ] Did you assign the right people for review (on the right)?
- [ ] Did you comply with the library style guidelines?

### CODE REVIEW

**Review by 19etweinstock — DISMISSED** [review]
Manufacturer name is incosistent between variants.
Symbol is not consistent with style guides.
Datasheet should be in style of non-adjustable voltage regulator
Please validate that this fits the d2pak package linked as I have seen parts claim to be d2pak but be different.

**Comment by zli909** [comment]
D2PAK validated. Manufacturer fixed. Datasheet fixed. Symbol origin and NAME location fixed.

**Comment by 19etweinstock** [comment]
Failed to port change to temp library

**Comment by zli909** [comment]
Done.

**Review by Arvind-Srinivasan — APPROVED** [review]
Approved

**Pull request merged**
